apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice-board
spec:
  selector:
    matchLabels:
      app: notice-board
  replicas: 4  # Start with 2 replicas
  template:
    metadata:
      labels:
        app: notice-board
    spec:
      containers:
      - name: notice-board
        image: notice-board:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"