---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential packages
  apt:
    name:
      - unzip
      - curl
      - software-properties-common
      - ufw
      - python3-pip
    state: present

- name: Configure UFW default policies
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Allow SSH
  ufw:
    rule: allow
    port: ssh
    proto: tcp